### ISSUE TITLE
Finalize taproot commitments once taproot is finalized

### ISSUE THREAD

**Issue by dr-orlovsky** [BP-WG/bp-core#2]
- [ ] https://github.com/LNP-BP/rust-lnpbp/tree/6010402f8e49fd05ad23f8c0e93ffe079d33d378/src/bp/dbc/scriptpubkey.rs#L228-L229
- [ ] https://github.com/LNP-BP/rust-lnpbp/tree/6010402f8e49fd05ad23f8c0e93ffe079d33d378/src/bp/scripts/types.rs#L598
- [ ] https://github.com/LNP-BP/rust-lnpbp/tree/6010402f8e49fd05ad23f8c0e93ffe079d33d378/src/bp/scripts/types.rs#L615
