### ISSUE TITLE
Implement sign-to-contract commitments

### ISSUE THREAD

**Issue by dr-orlovsky** [BP-WG/bp-core#6]
Prerequisites:

- [ ] S2C standard https://github.com/LNP-BP/LNPBPs/pull/118
- [ ] S2C commitments in Schnorr signatures inside `secp256k1` library.
       Implementation WIP: https://github.com/LNP-BP/secp256k1/tree/schnorr-commitments
       Previous work: https://github.com/bitcoin-core/secp256k1/pull/589
- [ ] S2C commitment scheme for MuSig2 and its implementation in `secp256k1-zkp`
- [ ] Rust code for ECDSA S2C from `secp256k1-zkp`
- [ ] Rust code for Schnorr S2C from `secp256k1`
