### ISSUE TITLE
Support Liquid and prospective layer 1 (Prime etc)

### ISSUE THREAD

**Issue by dr-orlovsky** [BP-WG/bp-core#62]
In order to abstract single-use-seals from a specific bitcoin layer 1 we should:
- [ ] Add supported chains to `Chain` type
- [ ] Create a non-exhaustive enumeration single-use seal type which lists possible seal formats
- [ ] Ensure single-use-seals always commit to the chain in its definition
- [ ] Provide seal resolver API taking chain information

**Comment by dr-orlovsky** [comment]
Not needed: the library is bitcoin only and all additional formats (like liquid) must be supported in the libraries above, like was done in https://github.com/RGB-WG/rgb-core/pull/183
